# values.yaml
environment: 2030-q3-1

pvc:
  name: internal-pvc-nfs
  storageSize: 1Gi

containerPort: 8080
service:
  port: 8080
  type: NodePort

envVariables:
  MY_ENV_VAR: "my-value"

cloudProvider: azure
pullSecretName: "acr-registry"

image:
  repository: acrarolibotnonprod.azurecr.io/automation/hello-world
  tag: latest

replicaCount: 1

serviceAccount:
  create: true
  name: my-service-account-name

ingress:
  enabled: false  

autoscaling:
  enabled: false