apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.pullSecretName }}
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: export_config
              value: {{ .Values.envVariables.export_config }}
          resources:
            limits:
              memory: 3000Mi
              cpu: 3000m
            requests:
              memory: 1500Mi
              cpu: 750m
          volumeMounts:
            - name: pvc-data
              mountPath: /opt/geoserver/data_dir/layerSources/automation/
              subPath: {{ .Values.subPathVolume }}
      volumes:
        - name: pvc-data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}

{{- if .Values.route.enabled }}
{{ .Files.Get "route.yaml" | nindent 2 }}
{{- end }}
