{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
  annotations:
{{ toYaml .Values.route.annotations | indent 4 }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
{{- end }}
